#!/bin/bash
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "        <meta http-equiv=\"refresh\" content=\"300\">"
echo "        <title>TCDS System Monitoring with RRDtool</title>"
echo "</head>"
echo "<body>"
echo ""
echo "<h1>Ph1 Pixel Crate Monitoring Daily Plots</h1>"
echo ""
echo "<table style=\"width:100%\">"
echo "        <tr>"
echo "                <td><a href=\"./crates.html\">Daily Plots</a></td>"
echo "                <td><a href=\"./crates-weekly.html\">Weekly Plots</a></td>"
echo "                <td><a href=\"./crates-monthly.html\">Monthly Plots</a></td>"
echo "                <td><a href=\"./crates_nic.html\">Control Hub Traffic Plots</a></td>"
echo "        </tr>"
echo "</table>"
echo ""
echo "<table style=\"width:100%\">"
echo ""
for rack in 's1g01' 's1g03' 's1g04'; do
    for crate in '45' '36' '27' '18'; do
	echo "  <tr>"
	echo "    <td><img src=\"./png/$rack-$crate-w-mchtemp.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-fmctemp.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-curr.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-12curr.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-v1.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-v2.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-v3.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-v4.png\"></td>"
	echo "    <td><img src=\"./png/$rack-$crate-w-vcc.png\"></td>"
	echo "  </tr>"
    done
done
echo ""
echo "  <tr>"
echo "    <td>&nbsp</td>"
echo "    <td>&nbsp</td>"
echo "  </tr>"
echo "</table>"
echo ""
echo "<table style=\"width:100%\">"
echo "        <tr>"
echo "                <td><a href=\"./crates.html\">Daily Plots</a></td>"
echo "                <td><a href=\"./crates-weekly.html\">Weekly Plots</a></td>"
echo "                <td><a href=\"./crates-monthly.html\">Monthly Plots</a></td>"
echo "                <td><a href=\"./crates_nic.html\">Control Hub Traffic Plots</a></td>"
echo "        </tr>"
echo "</table>"
echo ""
echo "</body>"
echo "</html>"